### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by twg-group** [2amigos/yii2-selectize-widget#15]
Hello! How can i add placeholder to the input field? (SelectizeDropDownList)
<pre>
echo SelectizeDropDownList::widget([
    'name' => 'items',
    'items' => ArrayHelper::map($items, 'item_id', 'name'),
    'options' => ['placeholder' => 'select please ...'],
    'clientOptions' => [
        'sortField' => 'text',
        'allowEmptyOption' => true
    ]
]);
</pre>

**Comment by twg-group** [comment]
it works!
<pre>
echo SelectizeDropDownList::widget([
    'name' => 'items',
    'items' => array_merge([''=>''], ArrayHelper::map($items, 'item_id', 'name')),
    'options' => ['id'=>'select-input', 'placeholder' => 'select please ...'],
    'clientOptions' => [
        'sortField' => 'text',
    ]
]);
</pre>

**Comment by mr-nicky** [comment]
Nice
