### ISSUE TITLE
double encoding of query get param

### ISSUE THREAD

**Issue by terazoid** [2amigos/yii2-selectize-widget#18]
https://github.com/2amigos/yii2-selectize-widget/blob/master/src/InputWidget.php#L47
function `$.getJSON` is automatically encoding all query params, so there is no need for `encodeURIComponent`

**Comment by tonydspaniard** [comment]
Thanks

**Comment by tonydspaniard** [comment]
Fixed on https://github.com/2amigos/yii2-selectize-widget/commit/b5fbf3d2574e017880dce6a9f813dee81ba3ebaa
