### ISSUE TITLE
SelectizeTextInput does not show previous selected tags

### ISSUE THREAD

**Issue by Karadox** [2amigos/yii2-selectize-widget#21]
Just updated to latest version and changed from Selectize to SelectizeTextInput.
But now when i add tags and want to edit them, they don't show up in the textinput.

They are saved and linked. When i do an implode to convert the array to a string, and put in the options array, the tags are displayed only the selectize filter doesn't work properly and only the first tag is not visible in the ddlb.

Could you enlighten me with the correct way so they are editable? Maybe an example to use it as a widget in activeform? Or this an actual bug and it isn't possible right now?

Code:
_form.php:

```
<?= $form->field($model, 'extensionNames')->widget(SelectizeTextInput::className(), [
    'loadUrl' => ['extensions/list'],
    'options' => ['class' => 'form-control'],
    'clientOptions' => [
        'plugins' => ['remove_button'],
        'valueField' => 'name',
        'labelField' => 'name',
        'searchField' => ['name'],
        'create' => true,
    ],
])->hint('Use commas to separate tags') ?>
```

**Comment by sanjarbek** [comment]
The same problem.

**Comment by enriquezafra** [comment]
Idem

**Comment by tonydspaniard** [comment]
@Karadox apologies for huge delay. checking.

**Comment by tonydspaniard** [comment]
@Karadox I have tried to replicate your issue but is working on my end: 

```php 
<?= $form->field($model, 'zip')->widget(
    SelectizeTextInput::className(),
    [
        'options' => ['class' => 'form-control'],
        'clientOptions' =>
            [
                'plugins' => ['remove_button'],
                'create' => true,
                'delimiter' => ',',
                'persist' => false,
                'createOnBlur' => true
            ]
    ]
)->hint('Use commas to delimit zip codes') ?>
```

The model, does have the 'zip' as a string but i could easily enhance this with the taggable behavior for example where i can store linked tag items. The only thing to do is to add a new virtual property ('tagNames'), make sure its set as 'safe' in rules and thats it. I cannot replicate your issue. Can any of you guys show me more code of your issue?
