### ISSUE TITLE
composer install fail

### ISSUE THREAD

**Issue by xjdata** [2amigos/yii2-selectize-widget#24]
Problem 1
    - 2amigos/yii2-selectize-widget 1.0.1 requires bower-asset/selectize ~0.12.0
 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.0 requires bower-asset/selectize ~0.12.0
 -> no matching package found.
    - Installation request for 2amigos/yii2-selectize-widget ^1.0 -> satisfiable
 by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1].

check https://github.com/brianreavis/selectize.js   

 see  

THIS REPO HAS MOVED → https://github.com/selectize/selectize.js

**Comment by xjdata** [comment]
e.....  is china internet problem .

**Comment by whisere** [comment]
I have the same problem again, followed the instruction here: http://yii2-usuario.readthedocs.io/en/latest/
and composer require 2amigos/yii2-usuario:~1.0
also try @dev and change stability  to dev,

still reports the same error above
