### ISSUE TITLE
share query property for search

### ISSUE THREAD

**Issue by lynicidn** [2amigos/yii2-selectize-widget#25]
https://github.com/2amigos/yii2-selectize-widget/blob/master/src/InputWidget.php#L47

``` js
{query: query}
```

change to

``` php
$query = isset($this->clientOptions['searchField']) ? : 'query';
'bla {' . $query . ': query} bla'
```

**Comment by lynicidn** [comment]
sorry, client options prop `searchField` can an array.
suggest share name, select2 use `q` and ur can change it

**Comment by tonydspaniard** [comment]
Couldn't understand. Do you mean that you wish to change its name?

**Comment by lynicidn** [comment]
you set hard `query` name for POST request.

rus: захардкорили параметр, к примеру селект2 шлет { q: "searchString" }
