### ISSUE TITLE
Dropdown not skinned properly for a second

### ISSUE THREAD

**Issue by kategee** [2amigos/yii2-selectize-widget#28]
Is there anyway to avoid being able to see the not properly skinned version of the dropdown?

On load the dropdown looks like this:
<img width="103" alt="screen shot 2016-08-25 at 3 01 16 pm" src="https://cloud.githubusercontent.com/assets/3019634/17982276/281d76bc-6ad5-11e6-9250-e89385a8c4c9.png">

After a second it pops in and it looks proper:
<img width="472" alt="screen shot 2016-08-25 at 3 04 35 pm" src="https://cloud.githubusercontent.com/assets/3019634/17982325/5bfcb1a0-6ad5-11e6-9bb7-826ed46603bc.png">

**Comment by tonydspaniard** [comment]
Unfortunately, that is the way the jquery plugin works. What I do is to provide a loader on my pages or set them hidden till the plugins are fired up.
