### ISSUE TITLE
Passing functions in clientOptions

### ISSUE THREAD

**Issue by tapaheh** [2amigos/yii2-selectize-widget#32]
Hi. Is it possible to pass functions in clientOptions, like `render`, `createFilter` and `create` in the [Email Contacts Selectize example](http://selectize.github.io/selectize.js/)?

Edit: Answering my own question, the solution is to use yii\web\JsExpression, i.e.
```
'render' => [
  'item' => new JsExpression("
    function(item, escape) {
      return '<div>' +item.name+'</div>';
   }")
]
```

**Comment by tonydspaniard** [comment]
Great @tapaheh
