### ISSUE TITLE
install problem 

### ISSUE THREAD

**Issue by whisere** [2amigos/yii2-selectize-widget#36]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-usuario 1.0.0 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.0-beta requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.1 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.10 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.11 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.12 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.13 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.2 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.3 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.4 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.5 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.6 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.7 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.8 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.9 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario dev-master requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-selectize-widget 1.0.x-dev requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.3 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.2 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.1 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - Installation request for 2amigos/yii2-usuario @dev -> satisfiable by 2amigos/yii2-usuario[1.0.0, 1.0.0-beta, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

#24

**Comment by tonydspaniard** [comment]
@whisere do you mind adding this to your composer: 

```
"minimum-stability": "dev",
"prefer-stable": true,
```

and tell me how it goes? Thanks

**Comment by whisere** [comment]
Thank you!
Updated here: https://github.com/2amigos/yii2-usuario/issues/63
