### ISSUE TITLE
Only shows single item in dropdown

### ISSUE THREAD

**Issue by jones6951** [2amigos/yii2-selectize-widget#9]
I am trying to use this widget to render a dropdown. However, the following code only shows a single item in the list, and I cannot select a different value.

    <?= $form->field($model, 'date_format')->widget(Selectize::className(), [
        'value' => 'dd/mm/yyyy,mm/dd/yyyy,yyyy-mm-dd,d M Y,M d, Y',
        'clientOptions' => [
            'maxItems' => 1,
        ],
    ]) ?>

**Comment by tonydspaniard** [comment]
You need to set `items` array not `value`
